version: '3'
services:
  php:
    build:
      context: ./
    command: php -S 0.0.0.0:8080
    working_dir: /app/public
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=initmongodb
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=root
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./.docker/mongo-volume:/data/dbls
    ports:
      - '27017-27019:27017-27019'
